name: 'Github Auto Release Creation'
description: 'Auto release creation action that will help you creating your code release automatically with several options parameter.'

inputs:
  release-type:
    description: 'Type of the release, it can be auto, manual, or custom.'
    required: true
    default: 'auto'
  minor-max-count:
    description: 'Minor change maximum count to update the major'
    required: true
    default: '21'

runs:
  using: 'docker'
  image: 'Dockerfile'

