name: Test Release Print Log


on:
  push:
    branches: 
      - main
      
jobs:
  test-run:
    runs-on: ubuntu-latest 
    steps:
      - name: Test Run
        uses: mokhlesurr031/auto-release@v1.1
        with:
          release-type: manual


